#!/usr/bin/env python
from random import randint
import sys

num = int(sys.argv[1])

nums = [randint(0, 2**32) for _ in range(num)]
maxn = max(nums)

print maxn
print 16
print 20
print num

first = nums.pop()
sys.stdout.write("{},{}\n".format(0, first))

for n in nums:
    m = randint(0, n)
    sys.stdout.write("{},{}\n".format(m, n))
